DEPLOYMENT ?= ragchat
LOCATION   ?= eastus2
# AI Search region. Split from LOCATION because Search capacity is often exhausted in a region
# independently of everything else. eastus2 (our LOCATION, for gpt-5-mini) has NO Search capacity
# region-wide, so Search lives in eastus — this default keeps deploy/release/whatif self-consistent.
# A Search service cannot change regions once created; override only for a fresh deployment elsewhere.
SEARCH_LOCATION ?= eastus
PARAMS     := infrastructure/main.bicepparam --parameters searchLocation=$(SEARCH_LOCATION)

RESOURCE_GROUPS := rg-ragchat-networking rg-ragchat-app rg-ragchat-ai rg-ragchat-monitoring

# Fetch one deployment output by name. ARM camel-cases output keys (APP_URL -> apP_URL), which breaks
# a case-sensitive JMESPath lookup — so resolve the key case-insensitively with jq (needs jq installed).
show = az deployment sub show -n $(DEPLOYMENT) -o json --query properties.outputs | jq -r --arg k "$(1)" '[to_entries[]|select(.key|ascii_downcase==($$k|ascii_downcase))][0].value.value'

# The app tier's resource group — home of the ACR. build/release resolve the registry from HERE rather
# than from deployment outputs, because a FAILED deployment record exposes no outputs, which would break
# any retry-after-failure (a failed release leaves exactly that state). The RG always survives, so this
# is self-healing. Precondition is unchanged: the ACR must already exist, i.e. run `make deploy` once first.
APP_RG    ?= rg-ragchat-app
acr_name  = az acr list -g $(APP_RG) --query "[0].name" -o tsv
acr_login = az acr list -g $(APP_RG) --query "[0].loginServer" -o tsv

.DEFAULT_GOAL := help
.PHONY: help preflight fmt lint whatif deploy build build-ingestion release seed ingest open workbook verify env destroy purge-apim

help:
	@grep -E '^[a-zA-Z_-]+:.*?## ' $(MAKEFILE_LIST) \
	  | awk 'BEGIN{FS=":.*?## "}{printf "  \033[36m%-16s\033[0m %s\n", $$1, $$2}'

preflight:
	@LOCATION="$(LOCATION)" bash scripts/preflight.sh

fmt: 
	az bicep format --file infrastructure/main.bicep

lint:
	az bicep lint --file infrastructure/main.bicep

whatif: 
	az deployment sub what-if -n $(DEPLOYMENT) --location $(LOCATION) --parameters $(PARAMS)

deploy:
	az deployment sub create -n $(DEPLOYMENT) --location $(LOCATION) --parameters $(PARAMS)

build:
	REG=$$($(acr_name)); \
	[ -n "$$REG" ] || { echo "no ACR found in $(APP_RG) — run 'make deploy' first"; exit 1; }; \
	az acr build -r $$REG -t ragchat:v1 ./app; \
	az acr build -r $$REG -t ragchat-ingestion:v1 ./ingestion

# Rebuild + push ONLY the ingestion image (the write-path Job). For an ingestion-only fix: the Job
# already points at the mutable ragchat-ingestion:v1 tag, so this + `make ingest` ships it — no redeploy.
build-ingestion:
	REG=$$($(acr_name)); \
	[ -n "$$REG" ] || { echo "no ACR found in $(APP_RG) — run 'make deploy' first"; exit 1; }; \
	az acr build -r $$REG -t ragchat-ingestion:v1 ./ingestion

release: build
	REG=$$($(acr_login)); \
	[ -n "$$REG" ] || { echo "no ACR found in $(APP_RG) — run 'make deploy' first"; exit 1; }; \
	az deployment sub create -n $(DEPLOYMENT) --location $(LOCATION) --parameters $(PARAMS) \
	  --parameters appImage=$$REG/ragchat:v1 ingestImage=$$REG/ragchat-ingestion:v1

seed: 
	STORAGE_ACCOUNT=$$($(call show,STORAGE_ACCOUNT)) uv run --script scripts/seed.py

ingest:
	az containerapp job start -n $$($(call show,INGEST_JOB_NAME)) -g $$($(call show,APP_RESOURCE_GROUP))

open:
	open $$($(call show,APP_URL))

workbook:
	@TENANT=$$(az account show --query tenantId -o tsv); \
	ID=$$($(call show,WORKBOOK_ID)); \
	[ -n "$$ID" ] || { echo "no WORKBOOK_ID output — run 'make deploy' first"; exit 1; }; \
	open "https://portal.azure.com/#@$$TENANT/resource$$ID/workbook"

env:
	@{ \
	  echo "# Generated by 'make env' from deployment '$(DEPLOYMENT)'. Do not commit (see .gitignore)."; \
	  echo "APIM_BASE_URL=$$($(call show,APIM_BASE_URL))"; \
	  echo "APIM_KEY=$$(az keyvault secret show --vault-name $$($(call show,KV_APP_NAME)) --name apim-subscription-key --query value -o tsv)"; \
	  echo "SEARCH_ENDPOINT=$$($(call show,SEARCH_ENDPOINT))"; \
	  echo "PG_HOST=$$($(call show,PG_HOST))"; \
	  echo "PG_USER=$$($(call show,UAMI_NAME))"; \
	  echo "PG_DB=$$($(call show,PG_DB))"; \
	  echo "BLOB_ACCOUNT=$$($(call show,STORAGE_ACCOUNT))"; \
	  echo "BLOB_CONTAINER=$$($(call show,BLOB_CONTAINER))"; \
	} > .env
	@echo "wrote .env — endpoints from deployment outputs, APIM_KEY read from kv-app (keyless)"

verify:
	@echo "storage allowSharedKeyAccess (want: false):"
	@az storage account show -n $$($(call show,STORAGE_ACCOUNT)) -g $$($(call show,APP_RESOURCE_GROUP)) \
	  --query allowSharedKeyAccess -o tsv
	@echo "deployment outputs (endpoints + names only — no secrets):"
	@az deployment sub show -n $(DEPLOYMENT) --query properties.outputs -o json

destroy:
	@echo "About to DELETE these resource groups and everything in them:"; \
	for rg in $(RESOURCE_GROUPS); do echo "  - $$rg"; done; \
	read -p "Type the deployment name ('$(DEPLOYMENT)') to confirm: " ans; \
	[ "$$ans" = "$(DEPLOYMENT)" ] || { echo "aborted."; exit 1; }; \
	echo "deleting resource groups in parallel — waiting for completion (APIM can take ~30-45 min) ..."; \
	for rg in $(RESOURCE_GROUPS); do \
	  ( az group delete -n $$rg --yes >/dev/null 2>&1 && echo "  deleted $$rg" || echo "  $$rg not found — skipping" ) & \
	done; \
	wait; \
	echo "removing the sub-scope deployment record (metadata only) ..."; \
	az deployment sub delete -n $(DEPLOYMENT) 2>/dev/null || echo "  (deployment '$(DEPLOYMENT)' not found — skipping)"; \
	echo "purging soft-deleted resources matching '$(DEPLOYMENT)' (they reserve their global names until purged) ..."; \
	TAB="$$(printf '\t')"; \
	az apim deletedservice list --query "[?contains(name,'$(DEPLOYMENT)')].[name,location]" -o tsv 2>/dev/null | while IFS="$$TAB" read -r n l; do \
	  loc=$$(echo "$$l" | tr '[:upper:]' '[:lower:]' | tr -d ' '); \
	  echo "  purging APIM $$n ($$loc)"; az apim deletedservice purge --service-name "$$n" --location "$$loc" >/dev/null; \
	done; \
	az cognitiveservices account list-deleted --query "[?contains(name,'$(DEPLOYMENT)')].[name,location,id]" -o tsv 2>/dev/null | while IFS="$$TAB" read -r n l id; do \
	  loc=$$(echo "$$l" | tr '[:upper:]' '[:lower:]' | tr -d ' '); \
	  rg=$$(echo "$$id" | sed -n 's#.*/resourceGroups/\([^/]*\)/.*#\1#p'); \
	  echo "  purging AI account $$n ($$loc, $$rg)"; az cognitiveservices account purge --name "$$n" --resource-group "$$rg" --location "$$loc" >/dev/null; \
	done; \
	az keyvault list-deleted --query "[?contains(name,'$(DEPLOYMENT)')].[name,properties.location]" -o tsv 2>/dev/null | while IFS="$$TAB" read -r n l; do \
	  loc=$$(echo "$$l" | tr '[:upper:]' '[:lower:]' | tr -d ' '); \
	  echo "  purging Key Vault $$n ($$loc)"; az keyvault purge --name "$$n" --location "$$loc" >/dev/null; \
	done; \
	echo "teardown complete — RGs gone, ghosts purged. Safe to 'make deploy LOCATION=<region>' anywhere."

purge-apim:
	@echo "soft-deleted APIM services in $(LOCATION):"; \
	az apim deletedservice list --query "[?location=='$(LOCATION)'].{name:name, scheduledPurgeDate:properties.scheduledPurgeDate}" -o table; \
	for name in $$(az apim deletedservice list --query "[?location=='$(LOCATION)'].name" -o tsv); do \
	  echo "purging $$name ..."; \
	  az apim deletedservice purge --service-name $$name --location $(LOCATION); \
	done
